version: '3.8'

services:

  # --- Your Database ---
  mysql:
    image: mysql:8.0
    container_name: bank-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bankdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Your Backend ---
  backend:
    build: ./backend
    container_name: bank-backend
    networks:
      - traefik-proxy
      - default
    volumes:
      - ./backend/src:/app/src
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
      - DB_DATABASE=bankdb
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.msabank-backend.rule=Host(`api-bank.mashaheir.com`)"
      - "traefik.http.routers.msabank-backend.entrypoints=websecure"
      - "traefik.http.routers.msabank-backend.tls.certresolver=myresolver"
      - "traefik.http.services.msabank-backend.loadbalancer.server.port=3000"

  # --- Your Frontend ---
  frontend:
    build: ./frontend
    container_name: bank-frontend
    networks:
      - traefik-proxy
    volumes:
      - ./frontend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=https://api-bank.mashaheir.com
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.msabank-frontend.rule=Host(`app-bank.mashaheir.com`)"
      - "traefik.http.routers.msabank-frontend.entrypoints=websecure"
      - "traefik.http.routers.msabank-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.msabank-frontend.loadbalancer.server.port=5173"

networks:
  traefik-proxy:
    external: true

volumes:
  mysql_data: